### PR TITLE
Config with default template

### PR DESCRIPTION
**Pull request by gforcada**
Now we are playing the same game but backwards, as we are not relying anymore on a centralized workflow, but rather we include them directly on the repository, we have to disable the central workflow from https://github.com/organizations/plone/settings/actions (only admins though).

We have __80__ repositories to go 🏃🏾 

This tests https://github.com/plone/meta/pull/102 🤞🏾

### CODE REVIEW

**Review by mauritsvanrees — APPROVED** [review]
LGTM

**Comment by mauritsvanrees** [comment]
@gforcada I added `[ci skip]` to the merge commit message, but that seems to have had no effect: `plone.event` is still added to the checkouts.

**Comment by gforcada** [comment]
🤔 I think it has to be `[ci-skip]` 😅 we can relax that of course, a PR in mr.robot will be needed though 😄

**Comment by gforcada** [comment]
🤔 the code is [on these lines](https://github.com/plone/mr.roboto/blob/master/src/mr.roboto/src/mr/roboto/views/runcorejob.py#L95-L98) and both `[ci skip]` and `[ci-skip]` are checked ...

**Comment by gforcada** [comment]
Oh, now I see 💡 (sleeping is always a great help to find solutions 😴 ).

`mr.roboto` gets two different events:

- whenever commits are pushed directly to a specific branch of a package that is being tracked by a `buildout.coredev` (i.e. someone pushes a commit to `master` branch in `plone.event`
- whenever an action happens in a PR, `mr.roboto` also gets notified and acts

For the first case, as I was mentioning, we do handle the case. A random commit on a branch with a `[ci-skip]` comment will not trigger a commit in `buildout.coredev`.

But a PR [getting merged will do it](https://github.com/plone/mr.roboto/blob/master/src/mr.roboto/src/mr/roboto/views/pull_requests.py#L42-L43): we need to add the same guard there.

**Pull request merged**
